#!/usr/bin/python
import pygtk
pygtk.require('2.0')
import gtk, gobject
import subprocess
import os, sys

from ConfigParser import SafeConfigParser, Error as CPError

#defaults, most can be over-ridden in opo.rc
OPO = './opo'
SCREENS = 4
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
X_SCREENS = 2
TIMEOUT = 20
CHOOSE_DIR = '.'
UNSTITCHED_DIR = '.'
ENCODER = 'mpeg4'
MUXER = None
#an approximate target for working out bps settings (for mpeg4/2-ish codecs)
#256 * 192 * 4 screens --> 192k * BYTES_PER_PIXEL_PER_SECOND bps
#1024 * 768 * 4 screens --> 3M * BYTES_PER_PIXEL_PER_SECOND bps
BYTES_PER_PIXEL_PER_SECOND = 2.5

RC_FILE = 'opo.rc'
AUTO_START = False
FULL_SCREEN = False

class OpoError(Exception):
    pass

def log(*messages):
    for m in messages:
        print >> sys.stderr, m

def name_suggester(dir, base, suffix):
    from os.path import join, exists
    for i in range(1, 999):
        name = "%s-%s.%s" % (base, i, suffix)
        fullname = join(dir, name)
        if not exists(fullname):
            return fullname
    raise OpoError("please: think up a name, or we'll be here forever")

def start_stitching_process(output_file, input_files, width, height,
                            audio_source=None, muxer=MUXER, encoder=ENCODER,
                            scale=1.0, clip_top=0, audio_codec='mp2',
                            progress_report=False):
    import urllib
    from urlparse import urlsplit
    try:
        for i, uri in enumerate(input_files):
            if not uri.startswith('file://'):
                fn = uri
                uri = 'file://' + urllib.quote(os.path.abspath(uri))
            else:
                fn = '/' + urllib.unquote(urlsplit(uri).path)#.decode('utf-8')
            #trigger exception if the filenamevdoesn't exist (so no http uris)
            open(fn).close()
            input_files[i] = uri
    except AttributeError, e: #"None has no attribute startswith"
        log(e)
        raise OpoError("Not all input files are specified")
    except IOError, e:
        raise OpoError(e)

    if muxer is None:
        try:
            muxer = output_file.rsplit('.', 1)[1]
        except IndexError:
            log('defaulting to avi muxer')
            muxer = 'avi'

    encoders = {
        'vp8': ['vp8enc', 'quality=8'],
        'mjpeg': ['jpegenc', 'idct-method=2', 'quality=85'],
        'mpeg1': ['mpeg2enc',], #XXX need to set bitrate, etc
        'theora': ['theoraenc',], #XXX settings
        'x264': ['x264enc', 'tune=fastdecode', 'quantizer=21'],
        'flv': ['ffenc_flv', "bitrate=%(bitrate)s"],  #XXX settings
        'mpeg4': ['ffenc_mpeg4', "bitrate=%(bitrate)s"],  #XXX settings
        'msmpeg4': ['ffenc_msmpeg4', "bitrate=%(bitrate)s"],#

        }
    details = {
        'bitrate': int(BYTES_PER_PIXEL_PER_SECOND * width * height * len(input_files)),
    }
    audio_codecs = {
        'vorbis': ['vorbisenc', 'bitrate=192', 'cbr=true', 'target=bitrate',],
        'mp3': ['lamemp3enc', 'bitrate=192', 'cbr=true', 'target=bitrate',],
        'mp2': ['twolame', 'bitrate=320'],
        'wav':['wavenc'],
        }
    muxers = {
        'avi': ['!', 'avimux', 'name=mux', ],
        'flv': ['!', 'flvmux', 'name=mux', ],
        'webm': ['!', 'webmmux', 'name=mux', ],
        'mpeg': ['!', 'mplex', 'name=mux', ],
    }
    muxers['mpg'] = muxers['mpeg']
    encoder_pipe = [s % details for s in encoders[encoder]]
    mux_pipe = [s % details for s in muxers[muxer]]
    if progress_report:
        progress_pipe = ['progressreport', '!']
    else:
        progress_pipe = []

    pipeline = (['gst-launch-0.10',
                 'videomixer',
                 'name=mix',
                 'background=1',
                 '!', 'ffmpegcolorspace',
                 '!',
                ] +
                progress_pipe +
                encoder_pipe +
                mux_pipe +
                ['!', 'filesink', 'location=%s' % output_file,])

    image_width = int(width * scale)
    image_height = int(height * scale)
    image_width_adj = (width - image_width) // 2


    for i, fn in enumerate(input_files):
        left = i * width + image_width_adj
        right = (len(input_files) - 1 - i) * width + image_width_adj
        top = clip_top
        if fn.endswith('Julia%20resize%204%2028th.mov'):
            top += top * 2 // 3

        if i != audio_source:
            pipeline.extend([
                'uridecodebin',
                'uri=%s' % fn,
                ])
        else:
            log("doing sound for %s" % i)
            pipeline.extend([
                'uridecodebin',
                'uri=%s' % fn,
                'name=demux',
                'demux.',
                '!', 'queue',
                '!'])
            pipeline.extend(audio_codecs[audio_codec])
            pipeline.extend(['!', 'mux.', 'demux.'])
        pipeline.extend([
            '!', 'deinterlace',
            '!', 'videoscale',
            '!', 'video/x-raw-yuv,', 'width=%s,' % image_width, 'height=%s' % image_height,
            ';', 'video/x-raw-rgb,', 'width=%s,' % image_width, 'height=%s' % image_height,
            '!', 'videobox', 'border-alpha=0', 'alpha=1', 'left=-%s' % left, 'right=-%s' % right,
            'top=%s' % top, 'bottom=%s' % (image_height - height - top),
            '!', 'queue',
            '!', 'mix.',
            ])

    log(' '.join(pipeline).replace('!', ' \\\n!').replace('. ', '.\\\n '))
    p = subprocess.Popen(pipeline)
    return p

class Launcher:
    is_auto = None
    auto_tick_id = None
    stitch_tick_id = None
    tiemout = TIMEOUT
    chooser = None

    def play(self, logfile=None):
        """Play the currently selected video"""
        os.environ['GST_DEBUG'] = '2'
        if logfile is not None:
            import time
            logfile = logfile.replace('$NOW', time.strftime('%Y-%m-%d+%H:%M:%S'))
            f = open(logfile, 'w')

        cmd = [OPO, '-s', str(self.screens), '-c', self.video,
               '-w', str(self.display_width), '-h', str(self.display_height)]
        if self.x_screens:
            cmd.extend(['-x', str(self.x_screens)])
        if self.force_multiscreen:
            cmd.append('-m')
        if self.full_screen:
            cmd.append('-f')
        log("Starting play: %r" % ' '.join(cmd))
        subprocess.call(cmd, stdout=f, stderr=subprocess.STDOUT)
        if logfile is not None:
            f.close()


    def on_play_now(self, widget, data=None):
        self.play(logfile="logs/opo-$NOW.log")

    def on_mode_switch(self, widget, data=None):
        """Turning auto mode on or off, according to the widget's
        state ('active' is auto).  If the widget is toggled to the
        current mode, ignore it."""
        auto = widget.get_active()
        if auto == self.is_auto:
            log("spurious auto toggle")
            return
        self.is_auto = auto
        for x in self.advanced_widgets:
            x.set_sensitive(not auto)
        if auto:
            self.start_auto_countdown()
        else:
            self.stop_auto_countdown()

    def start_auto_countdown(self):
        self.countdown = self.timeout
        if self.auto_tick_id is None: #lest, somehow, two ticks try going at once.
            self.auto_tick_id = gobject.timeout_add(1000, self.auto_tick)

    def stop_auto_countdown(self):
        if self.auto_tick_id is not None:
            gobject.source_remove(self.auto_tick_id)
            self.auto_tick_id = None
        self.mode_switch.set_label("Play _automatically in %s seconds" % self.timeout)

    def auto_tick(self):
        self.countdown -= 1
        if self.countdown > 0:
            if self.countdown == 1:
                self.mode_switch.set_label("Play _automatically in one second!")
            else:
                self.mode_switch.set_label("Play _automatically in %s seconds" % self.countdown)
            return True
        self.auto_tick_id = None
        self.play(logfile="logs/opo-auto-$NOW.log")
        #returning False stops countdown, which is perhaps irrelevant
        #as self.play should never return
        return False

    def on_chooser(self, widget, *data):
        self.video = widget.get_uri()
        self.update_heading()
        self.update_choose_dir(widget.get_current_folder())

    def stitch_video(self, widget, data=None):
        """Launch the video joining gstreamer process, show a progress
        bar/ spinner, and start a ticker that watches for its end."""
        log("stitching video !")
        output_file = self.stitch_target_field.get_text()
        input_files = [x.get_uri() for x in self.stitch_choosers]
        width = int(self.width_field.get_text())
        height = int(self.width_field.get_text())
        self.stitching_process = start_stitching_process(output_file, input_files,
                                                         width, height, self.stitch_audio_source)
        #self.stitching_process = subprocess.Popen(['sleep', '10'])
        self.progress_bar = gtk.ProgressBar()
        self.progress_bar.set_pulse_step(0.02)
        self.vbox.pack_start(self.progress_bar)
        self.stitch_button.hide()
        self.progress_bar.show()
        self.stitch_tick_id = gobject.timeout_add(150, self.stitch_tick, ouptput_file)
        self.currently_stitching = output_file

    def stitch_tick(self, output_file):
        """Spin the progress bar and wait for the finished video"""
        r = self.stitching_process.poll()
        if r is None:
            self.progress_bar.pulse()
            return True
        if r != 0:
            #XXX should catch and display gstreamer output
            log("got result %s" % r)
        self.progress_bar.hide()
        self.stitch_button.show()
        self.stitch_tick_id = None
        #XXX make the new video the chosen one

        v = self.currently_stitching = output_file
        if v[:7] == 'file://':
            v = v[7:]
        self.chooser.set_filename(v)
        self.update_choose_dir(dirname(v))
        return False

    def on_stitch_chooser(self, widget, n):
        """Unify the stitch_choosers current folder, unless they have video set"""
        d = widget.get_current_folder()
        for i in range(self.screens):
            if self.stitch_choosers[i].get_filename() is None:
                self.stitch_choosers[i].set_current_folder(d)
        return True

    def on_choose_stitch_target(self, widget, data=None):
        dialog = gtk.FileChooserDialog("Save as", action=gtk.FILE_CHOOSER_ACTION_SAVE,
                                       buttons=(gtk.STOCK_CANCEL, gtk.RESPONSE_REJECT,
                                                gtk.STOCK_OK, gtk.RESPONSE_ACCEPT)
                                       )
        dialog.set_do_overwrite_confirmation(True)
        if self.choose_dir:
            dialog.set_current_folder(self.choose_dir)

        response = dialog.run()
        filename = dialog.get_filename()
        if response in (gtk.RESPONSE_ACCEPT, gtk.RESPONSE_OK):
            directory, basename = os.path.split(filename)
            self.update_choose_dir(directory)
            self.stitch_target_field.set_text(dialog.get_filename())
        log(response)
        dialog.destroy()

    def on_stitch_audio_source(self, widget, n):
        self.stitch_audio_source = n

    def read_rc(self):
        rc = SafeConfigParser()
        rc.read(RC_FILE)
        def _get(section, item, default=None):
            try:
                return rc.get(section, item)
            except CPError, e:
                log(e)
                return default

        self.unstitched_dir = _get('Paths', 'unstitched_dir', UNSTITCHED_DIR)
        self.update_choose_dir(_get('Paths', 'choose_dir', CHOOSE_DIR))
        self.video = _get('Paths', 'last_played')
        self.timeout = int(_get('Misc', 'timeout', TIMEOUT))
        self.auto_start = _get('Misc', 'auto_start', '').lower() in ('true', '1', 'yes') or AUTO_START
        self.full_screen = _get('Display', 'full_screen', '').lower() in ('true', '1', 'yes') or FULL_SCREEN
        self.screens = int(_get('Display', 'screens', SCREENS))
        self.import_width = int(_get('Import', 'screen_width', SCREEN_WIDTH))
        self.import_height = int(_get('Import', 'screen_height', SCREEN_HEIGHT))
        self.display_width = int(_get('Display', 'screen_width', SCREEN_WIDTH))
        self.display_height = int(_get('Display', 'screen_height', SCREEN_HEIGHT))
        self.x_screens = int(_get('Display', 'x_screens', X_SCREENS))
        self.force_multiscreen = _get('Display', 'force_multiscreen', '').lower() in ('true', '1', 'yes')

    def write_rc(self):
        rc = SafeConfigParser()
        rc.read(RC_FILE)
        for section, key, value in (
            ('Paths', 'unstitched_dir', self.unstitched_dir),
            ('Paths', 'choose_dir', self.choose_dir),
            ('Paths', 'last_played', self.video),
            ):
            if value is not None:
                if not rc.has_section(section):
                    rc.add_section(section)
                rc.set(section, key, value)

        with open(RC_FILE, 'wb') as configfile:
            rc.write(configfile)

    def update_heading(self):
        try:
            video_name = self.video.rsplit('/', 1)[1]
            self.heading.set_markup('<big><b>%s</b> is ready to play</big>' %
                                    video_name)
            self.play_now.set_sensitive(True)
        except Exception, e:
            log("Couldn't set heading", e)
            self.heading.set_markup('<big>No video selected</big>')
            self.play_now.set_sensitive(False)

    def update_choose_dir(self, choosedir):
        self.choose_dir = choosedir
        if self.chooser:
            self.chooser.set_current_folder(choosedir)

    def make_window(self):
        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.set_border_width(15)
        self.vbox = gtk.VBox(False, 3)
        self.advanced_widgets = []

        _add = self.vbox.pack_start
        def _add_advanced(widget):
            self.vbox.pack_start(widget)
            self.advanced_widgets.append(widget)

        def _sep():
            # add a separator with slightly more space than usual
            _add(gtk.HSeparator(), True, True, 5)

        # heading
        h = gtk.Label()
        h.set_line_wrap(True)
        _add(h)
        self.heading = h

        self.play_now = gtk.Button("_Play now")
        self.play_now.connect("clicked", self.on_play_now, None)
        _add(self.play_now)
        _sep()

        #auto toggle
        self.mode_switch = gtk.CheckButton("Play _automatically in %s seconds" % self.timeout)
        self.mode_switch.connect("toggled", self.on_mode_switch, None)
        _add(self.mode_switch)
        _sep()

        #choose another
        #XXX file filters
        chooser_lab = gtk.Label("Ch_oose another combined video (%s screens)" % self.screens)
        chooser_lab.set_use_underline(True)
        chooser_lab.set_alignment(0, 0.5)
        self.chooser = gtk.FileChooserButton(title="video")
        if self.choose_dir:
            self.chooser.set_current_folder(self.choose_dir)
        self.chooser.set_width_chars(40)
        self.chooser.connect('file-set', self.on_chooser, None)

        chooser_lab.set_mnemonic_widget(self.chooser)

        _add_advanced(chooser_lab)
        _add_advanced(self.chooser)
        _sep()

        #create another by stitching subvideos
        nb = gtk.Label("Construct a _new combined video out of %s video files" % self.screens)
        nb.set_use_underline(True)

        nb.set_alignment(0, 0.5)
        _add_advanced(nb)

        sound = gtk.Label("Sound:")
        sound.set_alignment(0.99, 0.5)
        _add_advanced(sound)

        #hb = gtk.HBox()
        self.stitch_silent = gtk.RadioButton(None, "silent")
        self.stitch_silent.connect("toggled", self.on_stitch_audio_source, None)
        #hb.pack_start(self.stitch_silent, False)

        #XXX file filters
        self.stitch_choosers = []
        self.stitch_audio_source = None
        for i in range(self.screens):
            fc = gtk.FileChooserButton(title="video %s" % i)
            fcl = gtk.Label("Screen _%s" % (i + 1))
            fcl.set_use_underline(True)
            fcl.set_mnemonic_widget(fc)
            fc_sound = gtk.RadioButton(self.stitch_silent, "audio %s" % (i + 1,))
            fc_sound.set_active(False)
            fc_sound.set_tooltip_text("use the sound from video %s" % (i + 1,))
            fc_sound.connect("toggled", self.on_stitch_audio_source, i)
            fc_set = gtk.HBox()
            fc_set.pack_start(fcl, False)
            fc_set.pack_start(fc)
            fc_set.pack_start(fc_sound, False)
            self.stitch_choosers.append(fc)
            fc.connect('file-set', self.on_stitch_chooser, i)
            _add_advanced(fc_set)

        hb = gtk.HBox()
        #self.stitch_silent = gtk.RadioButton(None, "no sound")
        hb.pack_end(self.stitch_silent, False)
        _add_advanced(hb)


        #save_as box
        #XXX file filters
        self.stitch_target_field = gtk.Entry()
        self.stitch_target_field.set_width_chars(40)
        self.stitch_target_field.set_text(name_suggester(self.choose_dir, 'new', 'avi'))

        self.choose_stitch_target = gtk.Button(label="choose")
        self.choose_stitch_target.connect("clicked", self.on_choose_stitch_target, None)

        hb = gtk.HBox()
        name_label = gtk.Label("Save as")
        hb.pack_start(name_label, False)
        hb.pack_start(self.stitch_target_field)
        hb.pack_start(self.choose_stitch_target)
        nb.set_mnemonic_widget(self.stitch_choosers[0])
        _add_advanced(hb)

        #width/height boxes
        hb = gtk.HBox()
        label = gtk.Label("Pixel size of each screen: ")
        hb.pack_start(label, False)
        for name, default, label in (
            ('width_field', self.import_width, "_width"),
            ('height_field', self.import_height, "_height"),
            ):
            e = gtk.Entry()
            e.set_width_chars(5)
            e.set_alignment(1)
            e.set_text(str(default))
            setattr(self, name, e)
            lb = gtk.Label(label)
            lb.set_use_underline(True)
            lb.set_mnemonic_widget(e)
            hb.pack_start(lb, False)
            hb.pack_start(e, False)
        _add_advanced(hb)

        #stitch button
        self.stitch_button = gtk.Button("Assemble the new _video")
        self.stitch_button.connect("clicked", self.stitch_video, None)
        _add_advanced(self.stitch_button)

        self.window.add(self.vbox)

    def place_window(self):
        self.window.move(300, 50)

    def __init__(self):
        self.read_rc()
        self.make_window()
        self.place_window()
        self.update_heading()
        self.mode_switch.set_active(self.auto_start and self.video is not None)
        self.window.connect("destroy", self.destroy)
        self.window.show_all()


    def destroy(self, widget, data=None):
        log("bye")
        self.write_rc()
        gtk.main_quit()

    quit_onclick = destroy

if __name__ == '__main__':
    start = Launcher()
    gtk.main()
